server:
  port: 8888

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost/course?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/html/
    suffix: .html
    servlet:
      content-type: text/html
  redis:
    host: 127.0.0.1
    port: 6379
  mvc:
    static-path-pattern: /static/**

  mail:
    username: 2236913183@qq.com
    password: pkmtuxviblfeeceh
    host: smtp.qq.com
    properties:
      mail:
        smtl:
          ssl:
            enable: true
